server:
  port: 8183
  servlet:
    context-path: /simple-store-core

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tech_bazzar_core
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update

integrations:
  auth-service:
    url: http://localhost:8181/simple-store-auth/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
  cart-service:
    url: http://localhost:8182/simple-store-cart/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
